version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn install
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Build website
          command: yarn build:web
      - run:
          name: Build server
          command: yarn build:server
